# Generated by Django 6.1 on 2026-09-02 11:46

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('location_name', models.CharField(max_length=255)),
                ('location_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('map', 'Map'), ('search', 'Search')], default='gps', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('removed', 'Removed')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam'), ('fake', 'Fake report'), ('inappropriate', 'Inappropriate content'), ('wrong_information', 'Wrong information'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportManagementToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_token', to='reports.report')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'type', '-created_at'], name='reports_rep_status_9c252e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category', 'status'], name='reports_rep_categor_f6297b_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number', ''), _negated=True), name='report_phone_number_not_empty'),
        ),
        migrations.AddIndex(
            model_name='reportflag',
            index=models.Index(fields=['report', 'status'], name='reports_rep_report__2f9088_idx'),
        ),
        migrations.AddIndex(
            model_name='reportflag',
            index=models.Index(fields=['status', '-created_at'], name='reports_rep_status_21ed41_idx'),
        ),
        migrations.AddIndex(
            model_name='reportimage',
            index=models.Index(fields=['report', 'display_order'], name='reports_rep_report__b5c29b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmanagementtoken',
            index=models.Index(fields=['token_hash'], name='reports_rep_token_h_1855c7_idx'),
        ),
    ]
